services:
  runner-tuvi-online:
    build: ./runner
    env_file:
      - .env.tuvi-online
    environment:
      - RUNNER_NAME_PREFIX=${RUNNER_NAME_PREFIX:-docker-runner}
      - RUNNER_LABELS=${RUNNER_LABELS:-self-hosted,docker,linux}
      - RUNNER_WORKDIR=${RUNNER_WORKDIR:-/_runner/_work}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    mem_limit: 16g
    mem_reservation: 8g

  runner-tuvi-ansao:
    build: ./runner
    env_file:
      - .env.tuvi-ansao
    environment:
      - RUNNER_NAME_PREFIX=${RUNNER_NAME_PREFIX:-docker-runner}
      - RUNNER_LABELS=${RUNNER_LABELS:-self-hosted,docker,linux}
      - RUNNER_WORKDIR=${RUNNER_WORKDIR:-/_runner/_work}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: 5
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
